language:
    android
jdk:
    oraclejdk8
android:
    components:
        - tools
        - build-tools-23.0.2
        - android-22
        - extra-google-m2repository
        - extra-android-m2repository
script:
    ./gradlew test
before_install:
    - chmod +x gradlew
    - sudo pip install --upgrade pip
    - sudo pip install codecov
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
after_success:
    - codecov
